
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "blog_test",
    "author": "author_test",
    "url": "https://testblog.com",
    "likes": 50
}