
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pa2VUIiwiaWQiOiI2NDVhMmQyNzE4YzM1YzA4NWNiNWJhNjYiLCJpYXQiOjE2ODM2MzE0MDYsImV4cCI6MTY4MzYzNTAwNn0.bqT-Va1Y72po0eoZGfKSiOTOy7rWNfNgiDTd7ivr8bg

{
    "title": "Lazy Mikes Tuesday blog",
    "author": "Mike Tyson",
    "url": "https://tiger2.com",
    "likes": 150,
    "user": "6446683158589ed2fa86b3ee"
}

###

GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Sum Ting Wong",
    "name": "Wong",
    "password": "zxcv"
}

###
DELETE http://localhost:3003/api/blogs/6447b87d7211ca5ce185972e
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pa2VUIiwiaWQiOiI2NDVhMmQyNzE4YzM1YzA4NWNiNWJhNjYiLCJpYXQiOjE2ODM2MzE0MDYsImV4cCI6MTY4MzYzNTAwNn0.bqT-Va1Y72po0eoZGfKSiOTOy7rWNfNgiDTd7ivr8bg
