
GET  https://white-butterfly-5405.fly.dev/info

###
GET  https://white-butterfly-5405.fly.dev/api/persons/

###

DELETE  https://white-butterfly-5405.fly.dev/api/persons/4

###

GET   https://white-butterfly-5405.fly.dev/api/persons/4

###

POST  https://white-butterfly-5405.fly.dev/api/persons
Content-Type: application/json

{
    "name": "Peter Griffin",
    "number": "123-456-789"
}



###


###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/6434072f92672b3a054ea946

###

PUT http://localhost:3001/api/persons/6436b60caecbe56a5f84d7b1
Content-Type: application/json

{
    "name": "Billy",
    "number": "111"
}

###
POST  http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "invalid 2 digits",
    "number": "10-22-334455"
}

###
DELETE  http://localhost:3001/api/persons/6437ef0b7ea06d4ce2852f15

###

GET http://localhost:3001/api/persons